config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'categories#index'

  resources :howtos, only: [] do
    resources :products
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :categories, only: [:index] do
    resources :howtos, except:[:new]
  end
  resources :howto_likes, only: [:create, :destroy]
  resources :howto_favorites, only: [:create, :destroy]
  
  

  resources :category_relationships, only: [:create, :destroy]
  resources :category_suggestions, only: [:index, :create, :edit, :update, :destroy]
  resources :category_suggestion_votes, only: [:create, :destroy]

  namespace :admin, except: [:show] do
    resources :categories
  end

  resources :user_profiles, only: [:show, :edit, :update]
  resources :user_relationships, only: [:create, :destroy]

  get '/search_results', to: 'search_results#search'
  get '/about', to: 'static_pages#about'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


  def index
  end


  def about
  	respond_to do |format|
      format.html
      format.js
    end
  end

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_about_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Who we are, what we do, what we are trying to acheive</h4>
      </div>
      <div class="modal-body">
        <div class="wetal-about">
          <div class="wetal-about-top">
            <div class="wetal-about-top-profile-one">
              <div class="wetal-about-top-profile-one-picture">
                <%= image_tag 'Damien.jpg', class: 'img-responsive' %>
              </div>
              <div class="wetal-about-top-profile-one-info">
                <p><strong>Damien TALBOT</strong><br>Junior Software Developer</p>
              </div>
            </div>
            <div class="wetal-about-top-profile-two">
              <div class="wetal-about-top-profile-two-picture">
                <%= image_tag 'Fritz.jpg', class: 'img-responsive' %>
              </div>
              <div class="wetal-about-top-profile-two-info">
                <p><strong>Fritz DARES</strong><br>Junior Graphic Designer</p>
              </div>
            </div>
          </div>
          <br/><br/>
          <div class="wetal-about-bottom">
            <p>
              Wetal is a project created by Damien TALBOT and Fritz DARES about Do It Yourself (D.I.Y). We are both junior in our field but we wanted to use our skills together in order to create a project which take a place in our heart by now.
              <br/><br/>
              Wetal has been created to allow people to freely publish their own videos or to index videos via a YouTube link on the subject of Do It Yourself (D.I.Y). The content is classify by categories which allow the users to find all their favourite videos once they are on the website.
              <br/><br/>
              This is the very first version of Wetal, the next step is to go mobile (either by making an app or at least by optimizing the mobile version of this website). Our goal is to become the number one platform of D.I.Y in the world, we have some awesome features in mind but first thing first : we have to see if Wetal will please you guys. The website may have some bugs as we are not that much experienced but don't worry, there is nothing to make your computer crash. Wetal is a way to us to learn by doing.
              <br/><br/>
              Also, we would love to interact with you as this project is for you. What we mean by that is, we absolutely want you to get involved in the improvement of Wetal. So we expect you to get in touch with us either by email (<i>wetalapp@gmail.com</i>) or directly on social medias (on the left hand menu) in order to give us feedback in a positive or constructive way. We will be glad to discuss with you about our project.
              <br/><br/>
              Thank you for your support.
              <br/><br/>
              Cheers,<br/>Wetal team.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/about.js.erb
$('body').append('<%= j render partial: "static_pages/about_modal" %>');
$('#aboutModal').modal('show');

app/views/static_pages/index.html.erb
<div class="wave">
	
	<div class="frosty col-xs-10 col-xs-offset-1 text-center">
		<br/>
		<h1 style="text-shadow: 3px 3px #000; color: white;">
			<b>Find and create all your favorite<br/>D.I.Y right here guys !</b>
		</h1>
		<br /><br /><br />
		<br /><br /><br />
		<% if current_user && current_user.admin? %>
			<%= link_to 'Go to categories', admin_categories_path, class: 'btn btn-success btn-color' %>
		<% else %>
			<%= link_to 'Go to categories', categories_path, class: 'btn btn-success btn-color' %>
		<% end %>
		<br /><br /><br />
		<br /><br /><br />
		<h3 style="text-shadow: 3px 3px #000; color: white;">
			Wetal is the place where you can watch awesome D.I.Y, tutorials, howtos, crafts 
			from all over the world and create yours.
		</h3>
	</div>
</div>

<!--
<br />
<div class="col-xs-10 col-xs-offset-1 text-center">
  <div class="col-sm-6">
  	<h3>Top 3 Howtos</h3>
  	<br />      				
  	<div class="col-sm-4">
		Howto 1
	</div>
	<div class="col-sm-4">
		Howto 2
	</div>
    <div class="col-sm-4">
		Howto 2
	</div>
	<br /><br /><br />
	<%= link_to 'All Howtos', "#", class: 'btn btn-success' %>
  </div>

  <div class="col-sm-6">
    <h3>Top 3 Incoming Categories</h3>
    <br />
    <div class="col-sm-4">
		Category 1
	</div>
	<div class="col-sm-4">
		Category 2
	</div>
    <div class="col-sm-4">
		Category 2
	</div>
	<br /><br /><br />
	<%= link_to 'All Categories', "#", class: 'btn btn-success' %>
  </div>  
</div>
-->