config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'categories#index'

  resources :howtos, only: [] do
    resources :products
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :categories, only: [:index] do
    resources :howtos, except:[:new]
  end
  resources :howto_likes, only: [:create, :destroy]
  resources :howto_favorites, only: [:create, :destroy]
  
  

  resources :category_relationships, only: [:create, :destroy]
  resources :category_suggestions, only: [:index, :create, :edit, :update, :destroy]
  resources :category_suggestion_votes, only: [:create, :destroy]

  namespace :admin, except: [:show] do
    resources :categories
  end

  resources :user_profiles, only: [:show, :edit, :update]
  resources :user_relationships, only: [:create, :destroy]

  get '/search_results', to: 'search_results#search'
  get '/about', to: 'static_pages#about'

  

end

app/models/category.rb
class Category < ActiveRecord::Base


  validates :title, presence: true,  length: { minimum: 3 , maximum: 32}, uniqueness: true

  # has picture
  has_one :photo, :dependent => :destroy
  validates :photo, presence: true
  accepts_nested_attributes_for :photo

  # has picture many howtos
  has_many :howtos, :dependent => :destroy


  # users can follow a category
  has_many :passive_relationships, class_name:  "CategoryRelationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower



  def self.search(keyword)
    where("lower(title) like ?", "%#{keyword.downcase}%") 
  end


end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController


  before_action :authenticate_user!
  before_action :require_admin_authorization


  def index		
    # @categories = Category.all
    @categories = Category.paginate(:page => params[:page], :per_page => 8)
  end


  def new  	
  	@category = Category.new
    @category.photo = Photo.new
  end


  def create
    @category = Category.create(category_params)

    if @category.valid?
      redirect_to admin_categories_path
    else
      render :new, status: :unprocessable_entity
    end  
  end


  def edit
    @category = Category.find(params[:id])
  end


  def update
  	@category = Category.find(params[:id])
  	@category.update_attributes(category_params)
    redirect_to admin_categories_path
  end


  def destroy
  	@category = Category.find(params[:id])
  	@category.destroy
    redirect_to admin_categories_path
  end


  private

    def require_admin_authorization
      if !current_user.admin?
        return render text: 'Unauthorized', status: :unauthorized
      end
    end

    def category_params
      params.require(:category).permit(:title, :photo_attributes => [:picture])
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def index		
    # @categories = Category.all
    @categories = Category.paginate(:page => params[:page], :per_page => 8)
  end


  # def new  	
  # 	@category = Category.new
  #   @category.photo = Photo.new
  # end


  # def create
  #   @category = Category.create(category_params)

  #   if @category.valid?
  #     redirect_to categories_path
  #   else
  #     render :new, status: :unprocessable_entity
  #   end  
  # end


  # def edit
  #   @category = Category.find(params[:id])
  # end


  # def update
  # 	@category = Category.find(params[:id])
  # 	@category.update_attributes(category_params)
  # 	redirect_to categories_path
  # end


  # def destroy
  # 	@category = Category.find(params[:id])
  # 	@category.destroy
  # 	redirect_to categories_path
  # end


  private

    def category_params
      params.require(:category).permit(:title, :photo_attributes => [:picture])
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<h1>Edit your category</h1>

<%= simple_form_for @category, url: admin_category_path do |f| %>
	<%= f.input :title %>
	<%= f.simple_fields_for :photo do |sf| %>
		<%= sf.input :picture %>
	<% end %> 
	<br />
	<%= f.submit 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/admin/categories/index.html.erb
<div class="col-xs-10 col-xs-offset-1">
	<div class="col-sm-12 col-xs-12 ">
		<% if current_user && current_user.admin? %>
			<%= link_to 'New Category', new_admin_category_path, class: 'btn btn-primary pull-right' %>
		<% end %>
	</div>

	</br></br>


	<ul class="wetal-categories-list">
		<% @categories.each do |category| %>
			<li>
				<div class="wetal-categories-box-img">
					<% if category.photo.present? %>
						<%= image_tag category.photo.picture, :class => "img-responsive customized img-rounded" %>
					<% end %>
				</div>
				<div class="wetal-categories-box-bar">
					<h5><%= link_to category.title, category_howtos_path(category)%></h5>
					<%= image_tag 'Wetal-Follow.png', class: 'img-responsive' %>
					<span>
						<strong id="category_followers_<%= category.id %>"><%= category.followers.count %></strong> followers
					</span>
					<!-- <span><strong>100000</strong> followers</span>-->
					<div id="category_follow_form_<%= category.id %>">
						<% if current_user && current_user.following?(category) %>
							<%= render partial: 'shared/categories/unfollow', :object => @category = category %>
								<!--locals: { category: @category = category } %>-->
						<% else %>
							<%= render partial: 'shared/categories/follow', :object => @category = category %>
								<!--locals: { category: @category = category } %>-->
						<% end %>
					</div>
					<% if current_user && current_user.admin? %>
						<%= link_to edit_admin_category_path(category), class: 'btn btn-default btn-xs' do %>
								<span class="glyphicon glyphicon-wrench"></span>
						 <% end %>
						<%= link_to admin_category_path(category), method: :delete, 
							data: {confirm: 'Are you sure you want to delete this?'},
							class: 'btn btn-default btn-xs' do %>
								<span class="glyphicon glyphicon-trash"></span>
						<% end %>
				<% end %>
				</div>
			</li>
		<% end %>
	</ul>

	<div class="text-center">
  		<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
	</div>

</div>

app/views/admin/categories/new.html.erb
<h1>Enter your category's details</h1>

<%= simple_form_for @category, url: admin_categories_path do |f| %>
	<%= f.input :title %>
	<%= f.simple_fields_for :photo do |sf| %>
		<%= sf.input :picture %>
	<% end %>    
	<br />
	<%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>