config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'categories#index'

  resources :howtos, only: [] do
    resources :products
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :categories, only: [:index] do
    resources :howtos, except:[:new]
  end
  resources :howto_likes, only: [:create, :destroy]
  resources :howto_favorites, only: [:create, :destroy]
  
  

  resources :category_relationships, only: [:create, :destroy]
  resources :category_suggestions, only: [:index, :create, :edit, :update, :destroy]
  resources :category_suggestion_votes, only: [:create, :destroy]

  namespace :admin, except: [:show] do
    resources :categories
  end

  resources :user_profiles, only: [:show, :edit, :update]
  resources :user_relationships, only: [:create, :destroy]

  get '/search_results', to: 'search_results#search'
  get '/about', to: 'static_pages#about'

  

end

app/models/product.rb
class Product < ActiveRecord::Base

  
  validates :name, presence: true,  length: { minimum: 2 , maximum: 64 } #, uniqueness: true
  validates :link, presence: true
  validates :photo, presence: true
  

  has_one :photo, :dependent => :destroy
  accepts_nested_attributes_for :photo
  
  
  belongs_to :howto
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  before_action :authenticate_user!, only: [:new, :create]
  before_action :require_authorized_for_current_product, only: [:new, :create, :edit, :update, :destroy] 


	def index
	  @howto = Howto.find(params[:howto_id])
	  #@products = @howto.products
	end


  def new
    @howto = Howto.find(params[:howto_id])
    @product = Product.new
    @product.photo = Photo.new

    respond_to do |format|
      format.html
      format.js
    end
  end


	def create
	  @howto = Howto.find(params[:howto_id])
    @product = @howto.products.create(product_params)

    if @product.valid?
      flash[:notice] = "Your product has been created"
      redirect_to category_howtos_path(@howto.category)
      #redirect_to new_howto_product_path(@howto), format: 'js'
    else
      #render :new, status: :unprocessable_entity
      flash[:alert] = "Sorry, something went wrong. Your product hasn't been created."
      redirect_to category_howtos_path(@howto.category)
      #redirect_to new_howto_product_path(@howto), format: :js
    end
  end


  def edit
    @howto = Howto.find(params[:howto_id])
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end


  def update
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)

    if @product.valid?
      flash[:notice] = "Your product has been updated"
      redirect_to category_howtos_path(@product.howto.category_id)
    else
      flash[:alert] = "Sorry, something went wrong. Your product hasn't been upated."
      redirect_to category_howtos_path(@product.howto.category_id)
      #render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    @howto = Howto.find(params[:howto_id])
    @category = Category.find(@howto.category_id)
    redirect_to category_howtos_path(@category)
  end


	private

    def require_authorized_for_current_product
      if current_howto.user != current_user
        render text: "Unauthorized", status: :unauthorized
      end
    end

    helper_method :current_howto
    def current_howto
      @current_howto ||= Howto.find(params[:howto_id])
    end

    def product_params
      params.require(:product).permit(:name, :link, :photo_attributes => [:picture])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_edit_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="editProductFormModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Updating  <%= @product.name %></h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @product, url: howto_product_path(@howto, @product), 
          html: { multipart: true, novalidate: true } do |f| %>
          <%= f.input :name, label: false, placeholder: 'Name' %>
          <br/>
          <%= f.input :link, label: false, placeholder: 'Link to get this product' %>
          <br/>
          <div class="wetal-product-form-upload">
            <div class="wetal-product-form-upload-img">
              <%= image_tag 'picture-wetal.png', height: '32', width: '32', class: 'img-responsive' %>
            </div>
            <div class="wetal-product-form-upload-file">
              <div class="input-group">
                <label class="input-group-btn">
                  <span class="btn btn-default btn-file">
                      Browse
                       <input name="product[photo_attributes][picture]"  class="file required form-control upload"
                          id="product_photo_attributes_picture" type="file">
                  </span>
                  <input name="product_photo_file_name" id="uploadFile" type="text" 
                    class="form-control uploadFile" readonly>
                </label>
              </div>
            </div>
          </div>
          <br/><br/>
          <%= f.submit 'Create', class: 'btn btn-primary btn-color' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  $('#product_photo_attributes_picture').on('change', function() {
    var value = $(this).val().replace(/\\/g, '/').replace(/.*\//, '');
    $("#uploadFile").val(value);
  });

  $('#editProductFormModal').on('shown.bs.modal', function (e) {

    $(this).find('form').validate({
      rules: {
        'product[name]': {
          required: true,
          minlength: 2,
          maxlength: 64
        },
        'product[photo_attributes][picture]': {   // Why this rule ?
          required: true,             // I do not know !
          extension: "png|jpg|jpeg"       // but it doesn't work without it
        },
        'product_photo_file_name': {
          required: true,
          extension: "png|jpg|jpeg"
        },
        'product[link]': {
          required: true,
          url: true
        } 
      },
      messages: {
        'product[name]': {
          required: "Please enter a name for this product.",
          minlength: "The name must be at least 2 characters long.",
          maxlength: "The name must not exceed 64 characters long."
        },
        'product_photo_file_name': {
          required: "Please select a picture file.",
          extension: "Please select a file with one of these extensions : .png, .jpg, .jpg"
        },
        'product[link]': {
          required: "Please enter the URL where people can buy this product.",
          url: "Please enter a valide URL (e.g. http://www.example.com)"
        }
      },
      tooltip_options: {
        'product[name]': { placement: 'top' },
        'product_photo_file_name': { placement: 'top' },
        'product[link]': { placement: 'top' }
      },
    });
  });


  $('#editProductFormModal').on('hidden.bs.modal', function (e) {
      // clear form
      //$(this).find('form')[0].reset();
      // clear form tooltips
      //var $tooltip_div_elmts = $('.tooltip');
      //$tooltip_div_elmts.each(function() {
      //  $(this).remove();
      //});
      $("#editProductFormModal").remove();
  });
</script>

<style type="text/css">
  .btn-file {
      position: relative;
      overflow: hidden;
  }
  .btn-file input[type=file] {
      position: absolute;
      top: 0;
      right: 0;
      min-width: 100%;
      min-height: 100%;
      font-size: 100px;
      text-align: right;
      filter: alpha(opacity=0);
      opacity: 0;
      outline: none;
      background: white;
      cursor: inherit;
      display: block;
  }
</style>

app/views/products/_new_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="ProductFormModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New product for <%= @howto.title %></h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @product, url: howto_products_path(@howto), html: { multipart: true } do |f| %>
          <%= f.input :name, label: false, placeholder: 'Name' %>
          <br/>
          <%= f.input :link, label: false, placeholder: 'Link to get this product' %>
          <br/>
          <div class="wetal-product-form-upload">
            <div class="wetal-product-form-upload-img">
              <%= image_tag 'picture-wetal.png', height: '32', width: '32', class: 'img-responsive' %>
            </div>
            <div class="wetal-product-form-upload-file">
              <div class="input-group">
                <label class="input-group-btn">
                  <span class="btn btn-default btn-file">
                      Browse
                       <input name="product[photo_attributes][picture]"  class="file required form-control upload"
                          id="product_photo_attributes_picture" type="file">
                  </span>
                  <input name="product_photo_file_name" id="uploadFile" type="text" 
                    class="form-control uploadFile" readonly>
                </label>
              </div>
            </div>
          </div>
          <br/><br/>
          <%= f.submit 'Create', class: 'btn btn-primary btn-color' %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  
  $('#product_photo_attributes_picture').on('change', function() {
      var value = $(this).val().replace(/\\/g, '/').replace(/.*\//, '');
      $("#uploadFile").val(value);
    });
    

    $(document).ready(function(){

        $('#new_product').validate({
          rules: {
            'product[name]': {
              required: true,
              minlength: 2,
              maxlength: 64
            },
            'product[photo_attributes][picture]': {   // Why this rule ?
              required: true,             // I do not know !
              extension: "png|jpg|jpeg"       // but it doesn't work without it
            },
            'product_photo_file_name': {
              required: true,
              extension: "png|jpg|jpeg"
            },
            'product[link]': {
              required: true,
              url: true
            } 
          },
        messages: {
          'product[name]': {
            required: "Please enter a name for this product.",
            minlength: "The name must be at least 2 characters long.",
            maxlength: "The name must not exceed 64 characters long."
          },
          'product_photo_file_name': {
            required: "Please select a picture file.",
            extension: "Please select a file with one of these extensions : .png, .jpg, .jpg"
          },
          'product[link]': {
            required: "Please enter the URL where people can buy this product.",
            url: "Please enter a valide URL (e.g. http://www.example.com)"
          }
        },
        tooltip_options: {
                'product[name]': { placement: 'top' },
                'product_photo_file_name': { placement: 'top' },
                'product[link]': { placement: 'top' }
            },
        });
    })


  $('#ProductFormModal').on('hidden.bs.modal', function (e) {
      // clear form
      //$(this).find('form')[0].reset();
      // clear form tooltips
      //var $tooltip_div_elmts = $('.tooltip');
      //$tooltip_div_elmts.each(function() {
      //  $(this).remove();
      //});
      $("#ProductFormModal").remove();
    });
</script>

<style type="text/css">
  .btn-file {
      position: relative;
      overflow: hidden;
  }
  .btn-file input[type=file] {
      position: absolute;
      top: 0;
      right: 0;
      min-width: 100%;
      min-height: 100%;
      font-size: 100px;
      text-align: right;
      filter: alpha(opacity=0);
      opacity: 0;
      outline: none;
      background: white;
      cursor: inherit;
      display: block;
  }
</style>

app/views/products/edit.js.erb
$('body').append('<%= j render partial: "products/edit_modal", locals: { product: @product } %>');
$('#editProductFormModal').modal('show');

app/views/products/new.js.erb
$('body').append('<%= j render partial: "products/new_modal", locals: { product: @product } %>');
$('#ProductFormModal').modal('show');