config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'categories#index'

  resources :howtos, only: [] do
    resources :products
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :categories, only: [:index] do
    resources :howtos, except:[:new]
  end
  resources :howto_likes, only: [:create, :destroy]
  resources :howto_favorites, only: [:create, :destroy]
  
  

  resources :category_relationships, only: [:create, :destroy]
  resources :category_suggestions, only: [:index, :create, :edit, :update, :destroy]
  resources :category_suggestion_votes, only: [:create, :destroy]

  namespace :admin, except: [:show] do
    resources :categories
  end

  resources :user_profiles, only: [:show, :edit, :update]
  resources :user_relationships, only: [:create, :destroy]

  get '/search_results', to: 'search_results#search'
  get '/about', to: 'static_pages#about'

  

end

app/models/howto.rb
class Howto < ActiveRecord::Base



  validates :title, presence: true,  length: { maximum: 100 } #, uniqueness: true
  validates :description, presence: true,  length: { maximum: 1000 } #, uniqueness: true
  #validates :video, presence: true


  belongs_to :category


  has_one :video, :dependent => :destroy
  accepts_nested_attributes_for :video


  has_many :products, :dependent => :destroy

  belongs_to :user


  has_many :passive_howto_likes, class_name:  "HowtoLike",
                                   foreign_key: "liked_id",
                                   dependent:   :destroy
  has_many :likers, through: :passive_howto_likes, source: :liker


  has_many :passive_howto_favorites, class_name:  "HowtoFavorite",
                                   foreign_key: "admired_id",
                                   dependent:   :destroy
  has_many :admirers, through: :passive_howto_favorites, source: :admirer


  has_many :comments


  def self.search(keyword)
    where("lower(title) like ?", "%#{keyword.downcase}%") 
  end


end

app/controllers/howtos_controller.rb
class HowtosController < ApplicationController


  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy] #:new, 
  before_action :require_authorized_for_current_howto, only: [:edit, :update, :destroy]


  def index
    @category = Category.find(params[:category_id])
    #@howtos = @category.howtos
    @howtos = @category.howtos.paginate(:page => params[:page], :per_page => 8)
  end


  #def new
  #  @category = Category.find(params[:category_id])
  #  @howto = Howto.new
  #  @howto.video = Video.new
  #end


  def create
	  @category = Category.find(params[:category_id])
    
    @howto = @category.howtos.create(howto_params.merge(user: current_user))
    if @howto.valid?
      #redirect_to new_howto_product_path(@howto)
      flash[:notice] = "Don't forget to add products on your howto"
      redirect_to category_howtos_path(@category)
    else
      flash[:alert] = "Sorry, something went wrong. The howto hasn't been created."
      #render :new, status: :unprocessable_entity #was this line before but now there is no :new action anymore
      redirect_to category_howtos_path(@category)
    end
  end


  def show
  	@category = Category.find(params[:category_id])
  	@howto = Howto.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end


  def edit
    @category = Category.find(params[:category_id])
    @howto = Howto.find(params[:id])
    #if @howto.video.present?
    #  @filename = @howto.video.video.file.filename 
    #end

    respond_to do |format|
      format.html
      format.js
    end
  end


  def update
  	@category = Category.find(params[:category_id])
  	@howto = Howto.find(params[:id])
  	@howto.update_attributes(howto_params)

    if @howto.valid?
      redirect_to category_howtos_path(@category)
    else
      flash[:alert] = "Sorry, something went wrong. The howto hasn't been updated."
      redirect_to category_howtos_path(@category)
      #render :edit, status: :unprocessable_entity
    end
  end


  def destroy
  	@category = Category.find(params[:category_id])
  	@howto = Howto.find(params[:id])
  	@howto.destroy
  	redirect_to category_howtos_path(@category)
  end


  private

    def require_authorized_for_current_howto
      if current_howto.user != current_user
        render text: "Unauthorized", status: :unauthorized
      end
    end

    helper_method :current_howto
    def current_howto
      @current_howto ||= Howto.find(params[:id])
    end

    def howto_params
      params.require(:howto).permit(:title, :description, :for_sale, :link, :yt_embedded_link,
        :video_attributes => [:video])
    end
end

app/helpers/howtos_helper.rb
module HowtosHelper
end

app/views/howtos/edit.html.erb
<div class="col-xs-10 col-xs-offset-1">

	</br></br>

	<div class="wetal-howto-form">
		<%= simple_form_for @howto, url: category_howto_path(@category, @howto) do |f| %>
			<div class="wetal-howto-form-header">
				<h4>Step 1/2</h4>
				<h1>Howto</h1>
			</div>
			<div class="wetal-howto-form-left-block">
				<div class="wetal-howto-form-left-block-title">
					<%= f.input :title, label: false, placeholder: 'Title' %>
				</div>
				<div class="wetal-howto-form-left-block-desc">
					<%= f.input :description, label: false, placeholder: 'Description' %>
				</div>
				<div class="wetal-howto-form-left-block-media">
					<%= f.input :for_sale, as: :boolean %>
					<div id="link_div" style="display:none;">
						<%= f.input :link, label: false, placeholder: 'Link to get this howto' %>
					</div>
				</div>
			</div>
			<div class="wetal-howto-form-right-block">
				<div class="wetal-howto-form-right-block-container">
					<div class="wetal-howto-form-right-block-container-img">
						<%= image_tag 'camera-wetal.png', class: 'img-responsive' %>
					</div>
					<div class="wetal-howto-form-right-block-container-file">
						<%= f.simple_fields_for :video do |sf| %>
							<%= sf.input :video, label: false %>
						<% end %>
					</div>
				</div>
			</div>
			<%= f.submit 'Update', class: 'btn btn-primary' %>	
		<% end %>
	</div>

	<script type="text/javascript">
	  var checkbox = document.getElementById('howto_for_sale');
	  var link_div = document.getElementById('link_div');
	  checkbox.onchange = function() {
	     if(this.checked)
	     {
	       link_div.style['display'] = 'block';
	     } 
	     else
	     {
	       link_div.style['display'] = 'none';
	     }
	  };
	</script>
</div>


<!--
<h1>Edit your howto</h1>

<%= simple_form_for @howto, url: category_howto_path(@category, @howto) do |f| %>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.simple_fields_for :video do |sf| %>
		<%= sf.input :video %>
	<% end %>
	<%= f.input :for_sale,  as: :boolean %>
	<br />
	<%= f.submit 'Update', class: 'btn btn-primary' %>
<% end %>
-->

app/views/howtos/edit.js.erb
$('body').append('<%= j render partial: "shared/howtos/edit_modal", locals: { howto: @howto } %>');
$('#howtoEditModal').modal('show');

app/views/howtos/index.html.erb
<div class="col-xs-10 col-xs-offset-1">

	<div class="col-sm-12 col-xs-12">
		<h5 style="color: #8E2F01">
			<!--span class="label label-default" style="background-color: #8E2F01;color: white;"-->
				Howtos of the <%= @category.title %> category
			<!--/span-->
			<%= link_to 'Back to all categories', categories_path, 
			class: 'btn btn-primary btn-xs pull-right btn-color' %>
		</h5>
	</div>
	<br/><br/><br/>

	
	<%= render partial: 'shared/howtos/howtos_list' %>


	<div class="text-center">
  		<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
	</div>

</div>

app/views/howtos/show.js.erb
$('body').append('<%= j render partial: "shared/howtos/modal", locals: { howto: @howto } %>');
$('#howtoDetailModal').modal('show');